<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
	<Content Include="README.md" />
  </ItemGroup>

  <ItemGroup>
	<SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Respondeo.UnitTests" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Respondeo.Content.Shared\Respondeo.Content.Shared.csproj" />
  </ItemGroup>

</Project>
