<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

</Project>
