<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
	<SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Respondeo.UnitTests" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Markdig" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="YamlDotNet" />
  </ItemGroup>

</Project>
