<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	<SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="Respondeo.UnitTests" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Markdig" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Respondeo.Content.Abstractions\Respondeo.Content.Abstractions.csproj" />
  </ItemGroup>

</Project>
